# Generated by Django 4.0.4 on 2022-06-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0003_product_image_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
