# Generated by Django 4.0.4 on 2022-06-10 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0006_rename_products_image_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='buyer',
            new_name='buyers',
        ),
    ]
