# Generated by Django 4.0.4 on 2022-06-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0009_rename_image_image_image_url_alter_product_buyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.IntegerField(default=0),
        ),
    ]
